services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sentinela
      POSTGRES_USER: sentinela
      POSTGRES_PASSWORD: sentinela
    volumes:
      - ./k8s/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  ai:
    build: ./ai-service
    environment:
      DATABASE_URL: postgres://sentinela:sentinela@db:5432/sentinela
    depends_on:
      - db
    ports:
      - "8000:8000"

  backend:
    build: ./backend-rust
    environment:
      DATABASE_URL: postgres://sentinela:sentinela@db:5432/sentinela
      AI_URL: http://ai:8000
    depends_on:
      - db
      - ai
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
